---
- include: install/repo.yaml
- name: remove_old_versions_of_docker
  yum:
    pkg:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: removed

- name: Install docker-ce
  yum:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: installed

- name: enable dockerd
  systemd:
    name: docker
    state: started
    enabled: yes

- name: docker mirrors
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart dockerd
