---
- name: Change the hostname
  hostname:
    name: '{{ hostname|quote }}'

- name: Add ip into hosts file
  lineinfile:
    path: /etc/hosts
    line: '{{ item }} {{hostvars[item].hostname}}'
  with_items: '{{groups.all}}'

- name: Disabled firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Disabled SELinux
  selinux:
    policy: targeted
    state: permissive

- name: Disable swap in file
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\s+swap\s+swap\s+.*)$'
    replace: '# \1'

- name: Disable swap
  shell: |
    swapoff -a

- name: Kernel settings
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
  with_items:
    - {name: 'net.bridge.bridge-nf-call-ip6tables', value: '1'}
    - {name: 'net.bridge.bridge-nf-call-iptables', value: '1'}
    - {name: 'net.ipv4.ip_forward', value: '1'}

- include_tasks: mirrors.yaml
