---
- hosts: rs-a
  gather_facts: no
  vars:
      - version: 4.4.4
      - mysql_server: "127.0.0.1"
      - mysql_port: "3306"
      - mysql_root_password: ""
  tasks:
    - include: install/repo.yaml
    - include: ../database/mariadb/install/repo.yaml

    - name: Install MariaDB-10.4
      yum:
        update_cache: yes
        pkg:
          - MariaDB-client
          - MariaDB-server

    - name: Install zabbix-{{version}}
      yum:
        pkg:
          - zabbix-server-mysql-{{version}}
          - zabbix-web-mysql-{{version}}

    - name: Start mariadb services and enabled then
      service:
        name: mariadb
        state: restarted
        enabled: yes

    - name: Create zabbix database
      mysql_db:
          name: zabbix
          encoding: 'utf8'
          state: present

    - name: Import zabbix schema
      mysql_db:
          name: zabbix
          login_host: "127.0.0.1"
          login_user: "root"
          target: "/usr/share/doc/zabbix-server-*/create.sql.gz"
          state: "import"

