- name: Add China mirrors of Zabbix
  yum_repository:
      name: Zabbix
      description: Zabbix version
      baseurl: https://mirrors.aliyun.com/zabbix/zabbix/5.0/rhel/7/$basearch/
      gpgkey: https://mirrors.aliyun.com/zabbix/RPM-GPG-KEY-ZABBIX
      gpgcheck: no

- name: Add China mirrors of MariaDB10.4
  yum_repository:
      name: mariadb104
      description: 10.4 version of mariadb
      baseurl: https://mirrors.aliyun.com/mariadb/yum/10.4/centos7-amd64/
      gpgkey: https://mirrors.aliyun.com/mariadb/yum/RPM-GPG-KEY-MariaDB
      gpgcheck: yes

- name: Add China mirrors of Centos7 base
  get_url:
    url: http://mirrors.aliyun.com/repo/Centos-7.repo
    dest: /etc/yum.repos.d/CentOS7.repo

- name: Add China mirrors of epel-release
  get_url:
    url: http://mirrors.aliyun.com/repo/epel-7.repo
    dest: /etc/yum.repos.d/epel.repo
