---
- name: "Deploying Kubernetes"
  hosts: master node
  roles:
    - { role: 'k8s-init', when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'" }

- name: Install k8s on master
  hosts: master
  roles:
    - { role: 'k8s-master', when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'" }
