- name: Create www group
  group:
    name: www
    state: present

- name: Create www user
  user:
    name: www
    group: www
    state: present

- name: Build configure script.
  run_once: true
  command: >
    chdir={{ php_source_clone_dir }}
    ./buildconf --force

- name: Ensure Makefile is exists
  stat:
    path: "{{ php_source_clone_dir }}/Makefile"
  register: ensure_php_makefile_output

- name: Run configure script.
  run_once: true
  shell: >
    chdir={{ php_source_clone_dir }}
    {{ php_source_configure_command }}
  when: ensure_php_makefile_output.stat.exists == False

- name: Ensure php executable
  stat:
    path: "{{ php_source_clone_dir }}/sapi/cli/php"
  register: ensure_php_bin_output

- name: Make and install PHP.
  run_once: true
  command: >
    {{ item }}
    chdir={{ php_source_clone_dir }}
  with_items:
    - "{{ php_source_make_command }}"
    - make install
  when: ensure_php_bin_output.stat.exists == False

- include_tasks: configure_base.yml
- include_tasks: configure_php-fpm.yml