- name: Ensure .pkg_installed exists
  stat:
    path: /tmp/.pkg_installed
  register: pkg_installed

- name: Copy oniguruma package
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: oniguruma-6.8.2-1.el7.x86_64.rpm, dest: /tmp/oniguruma-6.8.2-1.el7.x86_64.rpm }
    - { src: oniguruma-devel-6.8.2-1.el7.x86_64.rpm, dest: /tmp/oniguruma-devel-6.8.2-1.el7.x86_64.rpm }
  
- name: Install oniguruma
  yum:
    name:  ['/tmp/oniguruma-6.8.2-1.el7.x86_64.rpm', '/tmp/oniguruma-devel-6.8.2-1.el7.x86_64.rpm']
    state: present


- name: Install base deps
  yum:
    update_cache: yes
    disable_gpg_check: yes
    pkg:
      - libevent-devel
      - pcre-devel
      - gcc
      - gcc-c++
      - make
      - libcurl-devel
      - curl-*
      - net-snmp*
      - libxml2-*
      - wget
      - tar
      - systemd-devel
      - cmake3
    state: present
  when: pkg_installed.stat.exists == False

# - name: Install zabbix deps
#   yum:
#     update_cache: yes
#     disable_gpg_check: yes
#     pkg:
#       - OpenIPMI
#       - OpenIPMI-libs
#       - OpenIPMI-devel
#       - OpenIPMI-modalias
#       - unixODBC
#       - fping
#     state: present
#   when: pkg_installed.stat.exists == False

- name: Install php72 deps
  yum:
    update_cache: yes
    disable_gpg_check: yes
    pkg:
      - libpqxx
      - libpqxx-devel
      - vim
      - pcre
      - libwebp-devel
      - pcre-devel
      - openssl
      - openssl-devel
      - libicu-devel
      - autoconf
      - libjpeg
      - libjpeg-devel
      - libpng
      - libpng-devel
      - freetype
      - freetype-devel
      - libxml2
      - libxml2-devel
      - zlib
      - zlib-devel
      - glibc
      - glibc-devel
      - glib2
      - glib2-devel
      - ncurses
      - ncurses-devel
      - curl-devel
      - krb5-devel
      - libidn
      - libidn-devel
      - openldap
      - openldap-devel
      - nss_ldap
      - jemalloc-devel
      - cmake
      - boost-devel
      - bison
      - automake
      - libevent
      - libevent-devel
      - gd
      - gd-devel
      - libtool*
      - libmcrypt
      - libmcrypt-devel
      - mcrypt
      - mhash
      - libxslt
      - libxslt-devel
      - readline
      - readline-devel
      - gmp
      - gmp-devel
      - libcurl
      - libcurl-devel
      - openjpeg-devel
      - autoconf
      - automake
      - libtool
      - bison
      - make
      - re2c
      - sqlite-devel
      - oniguruma-devel
      - curl-devel
      - recode-devel
      - aspell-devel
      - libxml2-devel
      - pkgconfig
      - libmcrypt-devel
      - t1lib-devel
      - libXpm-devel
      - libpng-devel
      - libjpeg-turbo-devel
      - bzip2-devel
      - openssl-devel
      - freetype-devel
      - libicu-devel
      - mariadb-devel
      - gmp-devel
  when: pkg_installed.stat.exists == False


- name: Create .pkg_installed dot file
  file:
    path: /tmp/.pkg_installed
    state: touch
