- name: Install base deps
  yum:
    update_cache: yes
    pkg:
      - php
      - php-gd
      - php-ldap
      - php-json
      - php-bcmath
      - php-mbstring
      - php-xml
      - libevent-devel
      - pcre-devel
      - gcc
      - gcc-c++
      - make
      - libcurl-devel
      - curl-*
      - net-snmp*
      - libxml2-*
      - wget
      - tar
      - systemd-devel
      - cmake3
    state: present

- name: Install zabbix deps
  yum:
    update_cache: yes
    disable_gpg_check: yes
    pkg:
      - OpenIPMI
      - OpenIPMI-libs
      - OpenIPMI-modalias
      - unixODBC
      - fping
      - libpqxx
    state: present

- name: Install php72 deps
  yum:
    update_cache: yes
    pkg:
      - libpqxx-devel
      - wget
      - vim
      - pcre
      - libwebp-devel
      - pcre-devel
      - openssl
      - openssl-devel
      - libicu-devel
      - gcc
      - gcc-c++
      - autoconf
      - libjpeg
      - libjpeg-devel
      - libpng
      - libpng-devel
      - freetype
      - freetype-devel
      - libxml2
      - libxml2-devel
      - zlib
      - zlib-devel
      - glibc
      - glibc-devel
      - glib2
      - glib2-devel
      - ncurses
      - ncurses-devel
      - curl
      - curl-devel
      - krb5-devel
      - libidn
      - libidn-devel
      - openldap
      - openldap-devel
      - nss_ldap
      - jemalloc-devel
      - cmake
      - boost-devel
      - bison
      - automake
      - libevent
      - libevent-devel
      - gd
      - gd-devel
      - libtool*
      - libmcrypt
      - libmcrypt-devel
      - mcrypt
      - mhash
      - libxslt
      - libxslt-devel
      - readline
      - readline-devel
      - gmp
      - gmp-devel
      - libcurl
      - libcurl-devel
      - openjpeg-devel
      - autoconf
      - automake
      - libtool
      - bison
      - make
      - re2c
      - sqlite-devel
      - oniguruma-devel
      - curl-devel
      - recode-devel
      - aspell-devel
      - libxml2-devel
      - pkgconfig
      - libmcrypt-devel
      - t1lib-devel
      - libXpm-devel
      - libpng-devel
      - libjpeg-turbo-devel
      - bzip2-devel
      - openssl-devel
      - freetype-devel
      - libicu-devel
      - mariadb-devel
      - gmp-devel