- name: Check source code pack exists
  stat:
    path: /tmp/php-7.4.9.tar.xz
  register: php_compress_file

- name: Check source code directory exists
  stat:
    path: /tmp/php-7.4.9
  register: php_directory


- name: Downloading php74 source code
  copy:
    src: php-7.4.9.tar.xz
    dest: /tmp/
  when: php_compress_file.stat.exists == False or php_directory.stat == False

- name: Unarchive php74 source code
  unarchive:
    src: /tmp/php-7.4.9.tar.xz
    dest: /tmp
    remote_src: yes

