---
- hosts: rs-a
  gather_facts: no
  tasks:
    - include: install/repo.yaml

    - name: Install MariaDB-10.4
      yum:
        update_cache: yes
        pkg:
          - MariaDB-client
          - MariaDB-server
    - name: Start mariadb services and enabled then
      service:
        name: mariadb
        state: restarted
        enabled: yes
