---

- include_tasks: yum-mirrors.yaml

- name: Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: Disable Firewalld
  systemd:
    name: firewalld
    state: stopped

- name: Disable Selinux
  command: 'setenforce 0'

- name: Start install zabbix
  yum:
    update_cache: yes
    disable_gpg_check: yes
    pkg:
      - MariaDB-client
      - MariaDB-server
      - MySQL-python
      - php-fpm
      - nginx
      - zabbix-server-mysql-{{zbx_version}}
      - zabbix-web-mysql-{{zbx_version}}
      - zabbix-web-{{ zbx_version }}
    state: installed

- name: Enable MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Create zabbix database
  mysql_db:
      name: zabbix
      login_port: '{{ mysql_port }}'
      login_host: '{{ mysql_host }}'
      login_user: '{{ mysql_super }}'
      login_password: '{{ mysql_super_pass }}'
      login_unix_socket: '{{ mysql_socket }}'
      encoding: 'utf8'
      state: present

- name: Create zabbix user
  mysql_user:
    login_user: '{{ mysql_super }}'
    login_password: '{{ mysql_super_pass }}'
    login_host: '{{ mysql_host }}'
    login_port: '{{ mysql_port }}'
    name: '{{ mysql_zbx_user }}'
    host: localhost
    priv: '*.*:ALL'
    password: '{{ mysql_zbx_pass }}'
    login_unix_socket: '{{ mysql_socket }}'
    state: present
  no_log: True

- name: Copy create.sql to remote host
  copy:
    src: create.sql
    dest: /tmp/create.sql

- name: Import zabbix schema
  mysql_db:
      name: zabbix
      login_host: '{{ mysql_host }}'
      login_user: '{{ mysql_super }}'
      login_port: '{{ mysql_port }}'
      login_password: '{{ mysql_super_pass }}'
      login_unix_socket: '{{ mysql_socket }}'
      target: '/tmp/create.sql'
      state: "import"

- name: Init Nginx settings
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'www.conf', dest: '/etc/php-fpm.d/www.conf' }
    - { src: 'nginx.conf', dest: '/etc/nginx/nginx.conf' }

- name: Restarted Nginx & php-fpm
  systemd:
    name: '{{ item }}'
    state: started
  with_items:
    - nginx
    - php-fpm

- name: Chown directory
  file:
    path: '{{ item }}'
    owner: nginx
    group: nginx
  with_items:
    - '/var/lib/php/session'
    - '/etc/zabbix/web'

- name: Init zabbix server config
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify:
    - enable zabbix-server
    - enable nginx
